services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: justdrinkjava-server
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_JWT_EXPIRATION=${APP_JWT_EXPIRATION}
      - SERVER_PORT=${SERVER_PORT}
      - LOGGING_LEVEL_WEB=${LOGGING_LEVEL_WEB}
      - LOGGING_LEVEL_SQL=${LOGGING_LEVEL_SQL}
      - LOGGING_LEVEL_HIBERNATE_BINDER=${LOGGING_LEVEL_HIBERNATE_BINDER}
      - LOGGING_LEVEL_APP=${LOGGING_LEVEL_APP}
    networks:
      - justdrink-network
    restart: unless-stopped

networks:
  justdrink-network:
    driver: bridge
