export { HomePage } from './HomePage/HomePage.page'
export { PostsPage } from './PostsPage/PostsPage.page'
export { AboutPage } from './AboutPage/AboutPage.page'
export { QuizzesPage } from './QuizzesPage/QuizzesPage.page'
export { LoginPage } from './LoginPage/LoginPage.page'
export { NotFoundPage } from './NotFoundPage/NotFoundPage.page' 