name: Test i Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-client:
    name: Client tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install root dependencies
      run: npm install --legacy-peer-deps
      
    - name: Install client dependencies
      working-directory: ./client
      run: npm install --legacy-peer-deps
        
    - name: Run client tests
      working-directory: ./client
      run: npm run test
      env:
        CI: true

  test-server:
    name: Server tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
        
    - name: Setup Maven wrapper
      working-directory: ./server
      run: chmod +x mvnw
      
    - name: Clean project
      working-directory: ./server
      run: ./mvnw clean
      
    - name: Download dependencies
      working-directory: ./server
      run: ./mvnw dependency:resolve
      
    - name: Compile project with Lombok
      working-directory: ./server
      run: ./mvnw compile -Dverbose=true
      
    - name: Run server tests with coverage
      working-directory: ./server
      run: ./mvnw test -Pcoverage
      env:
        SPRING_PROFILES_ACTIVE: test
        
    - name: Build server JAR
      working-directory: ./server
      run: ./mvnw package -DskipTests

  build-docker:
    name: Build Docker images
    needs: [test-client, test-server]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push client image
      uses: docker/build-push-action@v5
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: |
          ol1mowski187/justdrinkjava-client:latest
          ol1mowski187/justdrinkjava-client:${{ github.sha }}
          
    - name: Build and push server image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: |
          ol1mowski187/justdrinkjava-server:latest
          ol1mowski187/justdrinkjava-server:${{ github.sha }}
          
    - name: Notify about completion
      if: always()
      run: |
        echo "Build completed - Check GitHub Actions status" 