name: Test i Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Client tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install client dependencies and update package-lock.json
      run: |
        cd client
        npm install --legacy-peer-deps
        
    - name: Run client tests
      run: |
        cd client
        npm run test
      env:
        CI: true

  build-docker:
    name: Build Docker images
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push client image
      uses: docker/build-push-action@v5
      with:
        context: ./client
        file: ./Dockerfile
        push: true
        tags: |
          ol1mowski187/justdrinkjava-client:latest
          ol1mowski187/justdrinkjava-client:${{ github.sha }}
          
    - name: Notify about completion
      if: always()
      run: |
        echo "Build completed - Check GitHub Actions status" 