name: Test i Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-client:
    name: Client tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install root dependencies
      run: npm install --legacy-peer-deps
      
    - name: Install client dependencies
      working-directory: ./client
      run: npm install --legacy-peer-deps
        
    - name: Run client tests
      working-directory: ./client
      run: npm run test
      env:
        CI: true